/**
 * x402Adapter (§2.2) — IMPLEMENTED (Phase 3).
 *
 * Design note carried from §2.2: Razorpay settles in INR, not on-chain stablecoins, so
 * this adapter reinterprets x402's semantics. The envelope issued in the 402 response
 * encodes a Razorpay reference rather than a token contract address, and "payment
 * proof" is a signed reference to a Razorpay payment_id rather than an on-chain
 * transaction hash. x402's *shape* — a stateless HTTP challenge/response — is
 * rail-agnostic; only its reference implementation assumes crypto.
 *
 * ONE-TIME REDEMPTION: §3.2's final bullet says an x402 proof is "bound to a one-time
 * reference generated by the gateway itself" and can be redeemed "only once". That is
 * the same object as an AP2 mandate nonce — a single-use token minted for one request —
 * so the reference IS the nonce and flows through the same Redis + Postgres guard
 * rather than a second, parallel mechanism.
 */

import { randomUUID } from 'node:crypto';
import { redis } from '../redis/redis-client.js';
import { policyEngine } from '../policy/policy-engine.js';
import { prisma } from '../db/prisma-client.js';
import { createRazorpayOrderFor, isRecord, readNumber, readString } from './adapter-support.js';
import type {
  IncomingRequest,
  NormalizedPaymentRequest,
  ProtocolReceipt,
  RoutableProtocolAdapter,
  SettlementResult,
  ValidationFailureReason,
  ValidationResult,
} from './protocol-adapter.interface.js';

/** How long a 402 challenge stays redeemable. */
const CHALLENGE_TTL_SECONDS = 15 * 60;
const CHALLENGE_KEY_PREFIX = 'x402:challenge:';

/** The envelope returned in the PAYMENT-REQUIRED header (§2.4's worked example). */
export interface X402Envelope {
  readonly scheme: 'razorpay-inr';
  readonly amount: number;
  readonly currency: 'INR';
  readonly payTo: string;
  readonly expiry: string;
  readonly reference: string;
}

interface StoredChallenge {
  readonly reference: string;
  readonly cartId: string;
  readonly amountPaise: number;
  readonly merchantId: string;
  readonly agentIdentityId: string;
  readonly expiry: string;
}

export const X402_PAYMENT_REQUIRED_HEADER = 'payment-required';
export const X402_PAYMENT_SIGNATURE_HEADER = 'payment-signature';

function challengeKey(reference: string): string {
  return `${CHALLENGE_KEY_PREFIX}${reference}`;
}

/**
 * The challenge is held in Redis, which §2.1 already designates for exactly this class
 * of short-lived state. A stateless self-signed envelope would also work and would be
 * closer to x402's spirit, but it needs a dedicated gateway signing secret; that is a
 * deliberate future refinement, not an oversight.
 */
export async function storeChallenge(challenge: StoredChallenge): Promise<void> {
  await redis.set(
    challengeKey(challenge.reference),
    JSON.stringify(challenge),
    'EX',
    CHALLENGE_TTL_SECONDS,
  );
}

export async function loadChallenge(reference: string): Promise<StoredChallenge | null> {
  const raw = await redis.get(challengeKey(reference));
  if (raw === null) return null;
  try {
    const parsed: unknown = JSON.parse(raw);
    if (!isRecord(parsed)) return null;
    return parsed as unknown as StoredChallenge;
  } catch {
    return null;
  }
}

export class X402Adapter implements RoutableProtocolAdapter {
  readonly protocolName = 'x402' as const;
  readonly settlesViaHumanApproval = false;

  /** Detection is header-based: an x402 retry carries the payment proof header. */
  matches(request: IncomingRequest): boolean {
    return typeof request.headers[X402_PAYMENT_SIGNATURE_HEADER] === 'string';
  }

  /**
   * Mints the 402 challenge. The reference is gateway-generated and single-use, so a
   * proof can only ever be redeemed against the reference it was issued for (§3.2).
   */
  async issueChallenge(options: {
    cartId: string;
    amountPaise: number;
    merchantId: string;
    agentIdentityId: string;
    payTo: string;
  }): Promise<X402Envelope> {
    const reference = `pr_${randomUUID().replace(/-/g, '')}`;
    const expiry = new Date(Date.now() + CHALLENGE_TTL_SECONDS * 1000).toISOString();

    await storeChallenge({
      reference,
      cartId: options.cartId,
      amountPaise: options.amountPaise,
      merchantId: options.merchantId,
      agentIdentityId: options.agentIdentityId,
      expiry,
    });

    return {
      scheme: 'razorpay-inr',
      amount: options.amountPaise,
      currency: 'INR',
      payTo: options.payTo,
      expiry,
      reference,
    };
  }

  /**
   * §2.2: "parses the PAYMENT-SIGNATURE header, checks the payment envelope against
   * what the gateway originally issued in its 402 response, and rejects anything past
   * expiry."
   *
   * The proof is a JSON object carrying the reference plus the Razorpay payment
   * reference that stands in for an on-chain transaction hash.
   */
  async validate(rawRequest: IncomingRequest): Promise<ValidationResult> {
    const header = rawRequest.headers[X402_PAYMENT_SIGNATURE_HEADER];

    if (typeof header !== 'string') {
      return this.reject('malformed_request', { reason: 'missing PAYMENT-SIGNATURE header' });
    }

    let proof: unknown;
    try {
      proof = JSON.parse(header) as unknown;
    } catch {
      return this.reject('malformed_request', { reason: 'PAYMENT-SIGNATURE is not valid JSON' });
    }

    const reference = readString(proof, 'reference');
    if (reference === null) {
      return this.reject('malformed_request', { reason: 'proof carries no reference' });
    }

    const challenge = await loadChallenge(reference);
    if (challenge === null) {
      // Either never issued, already expired out of Redis, or already redeemed.
      return this.reject('envelope_mismatch', { reference });
    }

    const expiresAt = new Date(challenge.expiry);
    if (expiresAt.getTime() <= rawRequest.receivedAt.getTime()) {
      return this.reject('mandate_expired', { reference, expiry: challenge.expiry });
    }

    // The claimed amount must match what the gateway itself issued — an agent cannot
    // negotiate the price down by restating it in the proof.
    const claimedAmount = readNumber(proof, 'amount');
    if (claimedAmount !== null && claimedAmount !== challenge.amountPaise) {
      return this.reject('envelope_mismatch', {
        reference,
        expected: challenge.amountPaise,
        received: claimedAmount,
      });
    }

    const cartId = rawRequest.params['cartId'];
    if (cartId !== undefined && cartId !== challenge.cartId) {
      return this.reject('envelope_mismatch', {
        reference,
        expectedCart: challenge.cartId,
        receivedCart: cartId,
      });
    }

    const agent = await prisma.agentIdentity.findUnique({
      where: { id: challenge.agentIdentityId },
      select: { id: true, merchantId: true },
    });

    if (agent === null) {
      return this.reject('unknown_agent', { agentIdentityId: challenge.agentIdentityId });
    }

    return {
      ok: true,
      protocol: this.protocolName,
      request: rawRequest,
      claims: {
        merchantId: agent.merchantId,
        agentIdentityId: agent.id,
        amountPaise: challenge.amountPaise,
        // The reference IS the nonce — one-time redemption rides the §3.2 guard.
        nonce: reference,
        expiresAt,
        canonicalPayload: JSON.stringify(challenge),
        signature: readString(proof, 'razorpayPaymentId') ?? reference,
        raw: { proof, challenge } as Record<string, unknown>,
      },
    };
  }

  async normalize(validated: ValidationResult): Promise<NormalizedPaymentRequest> {
    if (!validated.ok) {
      throw new Error('normalize() called with a failed ValidationResult');
    }

    const { claims } = validated;
    const requiresHumanApproval = await policyEngine.exceedsAutoApproveCeiling(
      claims.agentIdentityId,
      claims.amountPaise,
    );

    return {
      merchantId: claims.merchantId,
      agentIdentityId: claims.agentIdentityId,
      amountPaise: claims.amountPaise,
      currency: 'INR',
      idempotencyKey: '', // derived by the pipeline from §3.3's formula
      sourceProtocol: 'x402',
      requiresHumanApproval,
      metadata: { ...claims.raw },
    };
  }

  /** Same settlement path as AP2 — one Razorpay Order, confirmed later by webhook (§1.3). */
  async settle(normalized: NormalizedPaymentRequest): Promise<SettlementResult> {
    return createRazorpayOrderFor(normalized);
  }

  async formatReceipt(result: SettlementResult): Promise<ProtocolReceipt> {
    return {
      protocol: 'x402',
      paymentRequestId: result.paymentRequestId,
      shape: {
        scheme: 'razorpay-inr',
        status: result.status,
        amount: result.amountPaise,
        currency: result.currency,
        reference: result.paymentRequestId,
        razorpayOrderId: result.razorpayOrderId,
        razorpayPaymentId: result.razorpayPaymentId,
      },
      issuedAt: new Date(),
    };
  }

  private reject(
    reason: ValidationFailureReason,
    detail: Record<string, unknown>,
  ): ValidationResult {
    return { ok: false, protocol: this.protocolName, reason, detail };
  }
}

export const x402Adapter = new X402Adapter();
